# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6531391b98230981a0668da34f12ede918440747d2e44d89a0a2140d885bdad1b4d687f211eb24d336c88337d24f21c7582d24565ae1b2a7845e6ab1331a1a24

test:
  secret_key_base: e531756b26b3f372a6170ca48f198f005c717ae8c43001f6277a1f2be1756b517c8585eb994f88c26433d161eb66e637be2247f377d6b66dcdc8afe0e5e4799f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
